# Generated by Django 2.2.5 on 2019-11-10 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runningelephant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_player_friends_+', to='runningelephant.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='starsign',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='thoughts',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
